# Generated by Django 6.1 on 2026-08-31 22:54

import csv_host.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional human-readable title for the CSV file', max_length=255)),
                ('file', models.FileField(help_text='Upload a .csv file', upload_to='csvs/', validators=[csv_host.models.validate_csv_extension])),
                ('description', models.TextField(blank=True, help_text='Optional description of the dataset')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CSV File',
                'verbose_name_plural': 'CSV Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
